# Generated by Django 3.1 on 2020-09-01 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='completion_date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
