# Generated by Django 3.1 on 2020-09-08 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20200901_0746'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='todo',
            table='todo',
        ),
    ]
