# Generated by Django 3.1 on 2020-09-08 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_auto_20200908_1250'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='todo',
            table=None,
        ),
    ]
