# Generated by Django 3.1.1 on 2020-09-15 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_auto_20200915_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='comment',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
